<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\antropology.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/assets/antropology-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-8, 0, 30]} rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.base_1.geometry} material={gltf.materials.FrontColor} />
      <T.Mesh
        geometry={gltf.nodes.base_2.geometry}
        material={gltf.materials['tripo_material_0f3f297f-adba-4203-838a-78fb11145382']}
      />
      <T.Mesh
        geometry={gltf.nodes.base_3.geometry}
        material={gltf.materials['tripo_material_0093946a-23ba-4d42-9d33-3d2c56fe4911']}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
