<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\cilindro.glb -T
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  import { controls } from "../../../stores/stores";

  export const ref = new Group();

  const gltf = useGltf("assets/cilindro-transformed.glb", { useDraco: true });

  const component = forwardEventHandlers();

  //   {
  //     "position": {
  //         "x": 9,
  //         "y": -4,
  //         "z": -9
  //     },
  //     "rotation": {
  //         "x": 1.7391304347826086,
  //         "y": 0,
  //         "z": 0
  //     }
  // }
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      position={[9, -4, -9]}
      rotation={[1.7391304347826086, 0, 0]}
      scale.z={4}
      geometry={gltf.nodes.cilindo.geometry}
      material={gltf.materials.FrontColor}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
