<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\mayor.glb -T
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { HTML, useGltf } from "@threlte/extras";
  // import { controls } from "../../../stores/stores";

  export const ref = new Group();

  const gltf = useGltf("assets/mayor-transformed.glb", { useDraco: true });

  const component = forwardEventHandlers();

  let controls = {
    position: {
      x: -1,
      y: 0,
      z: -40,
    },
    rotation: {
      x: 0.06,
      y: 5.434782608695652,
      z: 0,
    },
  };

  let showDialog1 = false;
  let showDialog2 = false;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group
      rotation={[controls.rotation.x, controls.rotation.y, controls.rotation.z]}
      position={[controls.position.x, controls.position.y, controls.position.z]}
      scale={[5, 5, 5]}
      name="mayor"
    >
      <T.Mesh
        geometry={gltf.nodes.geometry_0.geometry}
        material={gltf.materials.Material_0}
        position={[2, 0, 0]}
        rotation={[Math.PI, -1.5, Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes["tripo_node_000d3b46-8538-4f86-8917-2fd001ee39c1"]
          .geometry}
        material={gltf.materials[
          "tripo_material_000d3b46-8538-4f86-8917-2fd001ee39c1"
        ]}
        position={[-2, 0, 0]}
        rotation={[-Math.PI, 1.07, -Math.PI]}
      />
    </T.Group>

    <T.Group>
      <HTML transform position={[4, 3.5, 0]} rotation={[0, 0, 0]}>
        <button
          on:click={() => (showDialog1 = !showDialog1)}
          class=" cursor-pointer bg-black text-white font-bold rounded-md px-4 py-2"
          >Tlaloc</button
        >
      </HTML>

      {#if showDialog1}
        <HTML transform position={[9.3, 1, 0]} rotation={[0, 0, 0]}>
          <div
            class="w-[500px] bg-black text-white font-semibold p-2 rounded-md"
          >
            <p>
              <span class="text-yellow-400">Tlaloc</span> was the Aztec god of rain,
              water, and fertility, essential for agriculture. He was believed to
              control storms and provide life-giving rains but could also bring floods
              and destruction. Worship of Tlaloc included offerings and ceremonies
              to ensure good harvests.
            </p>
          </div>
        </HTML>
      {/if}
    </T.Group>

    <T.Group>
      <HTML transform position={[-4, 3.5, 0]} rotation={[0, 0, 0]}>
        <button
          on:click={() => (showDialog2 = !showDialog2)}
          class=" cursor-pointer bg-black text-white font-bold rounded-md px-4 py-2"
          >Xiuhcoatl</button
        >
      </HTML>

      {#if showDialog2}
        <HTML transform position={[-9.3, 1, 0]} rotation={[0, 0, 0]}>
          <div
            class="w-[500px] bg-black text-white font-semibold p-2 rounded-md"
          >
            <p>
              <span class="text-yellow-400">Xiuhcoatl</span>, in Aztec mythology, was a mythical serpent
              associated with fire, drought, and the sun. Known as the
              "Turquoise Serpent," it symbolized the fiery weapon of
              Huitzilopochtli, the god of war and the sun, used to defeat his
              enemies. It also represented transformation and cosmic energy.
            </p>
          </div>
        </HTML>
      {/if}
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
