<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\munal.glb -T
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { HTML, useGltf } from "@threlte/extras";
  // import { controls } from "../../../stores/stores";

  export const ref = new Group();

  const gltf = useGltf("/assets/munal-transformed.glb", { useDraco: true });

  const component = forwardEventHandlers();

  let controls = {
    position: {
      x: -8.5,
      y: -4.3,
      z: 0,
    },
    rotation: {
      x: 0,
      y: 4.891304347826087,
      z: 5.978260869565217,
    },
  };

  let showDialog = false;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes["tripo_node_045b78fd-3dd8-42d4-a175-9c99d2f442a0"]
        .geometry}
      material={gltf.materials[
        "tripo_mat_045b78fd-3dd8-42d4-a175-9c99d2f442a0"
      ]}
      position={[controls.position.x, controls.position.y, controls.position.z]}
      rotation={[controls.rotation.x, controls.rotation.y, controls.rotation.z]}
      scale={[5, 5, 5]}
    />

    <T.Group position={[-5, -2, 0]}>
      <HTML transform position={[0, 0, 0]} rotation={[0, 0, 0]}>
        <button
          on:click={() => (showDialog = !showDialog)}
          class=" cursor-pointer bg-black text-white font-bold rounded-md px-4 py-2"
          >Gliptoteca</button
        >
      </HTML>

      {#if showDialog}
        <HTML transform position={[4.9, -3, 0]} rotation={[0, 0, 0]}>
          <div
            class="w-[500px] bg-black text-white font-semibold p-2 rounded-md"
          >
            <p>
              <span class="text-yellow-400">
                The National Museum of Art (MUNAL)</span
              > is a must-visit for its stunning architecture and extensive collection
              of Mexican art. One highlight is the Gliptoteca, located on the first
              floor in Room 22. The term "Gliptoteca" comes from the Greek words
              gliptos (carved or sculpted stones) and theca (place), referring to
              a space for admiring a collection of sculptures and their stylistic
              connections.
            </p>
          </div>
        </HTML>
      {/if}
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
