<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\soumaya.glb -T
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, HTML } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("assets/soumaya-transformed.glb", { useDraco: true });

  const component = forwardEventHandlers();

  let controls = {
    position: {
      x: 12,
      y: -4,
      z: 0,
    },
    rotation: {
      x: 0,
      y: 4.782608695652174,
      z: 5.978260869565217,
    },
  };

  let showDialog = false;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.geometry_0002.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[controls.position.x, controls.position.y, controls.position.z]}
      rotation={[controls.rotation.x, controls.rotation.y, controls.rotation.z]}
      scale={[5, 5, 5]}
    />

    <T.Group>
      <HTML transform position={[9, -2.5, 0]} rotation={[0, 0, 0]}>
        <button
          on:click={() => (showDialog = !showDialog)}
          class=" cursor-pointer bg-black text-white font-bold rounded-md px-4 py-2"
          >The Thinker</button
        >
      </HTML>

      {#if showDialog}
        <HTML transform position={[4.3, -5.5, 0]} rotation={[0, 0, 0]}>
          <div
            class="w-[500px] bg-black text-white font-semibold p-2 rounded-md"
          >
            <p>
              <span class="text-yellow-400">The Thinker by Auguste Rodin</span>,
              displayed at the Soumaya Museum in Mexico City, is one of the most
              iconic sculptures in art history. Originally part of The Gates of
              Hell, inspired by Dante's Divine Comedy, it represents deep
              reflection and the complexity of human thought. The museum's piece
              is an authorized casting of Rodin's original work.
            </p>
          </div>
        </HTML>
      {/if}
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
